<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ZnpiwV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ZnpiwV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7ZnpiwV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7ZnpiwV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7ZnpiwV\App_KernelDevDebugContainer([
    'container.build_hash' => '7ZnpiwV',
    'container.build_id' => '494f13a5',
    'container.build_time' => 1739181314,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7ZnpiwV');
